name: Build

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.20.0
          cache: "npm"
      
      - name: Install NPM dependencies
        run: npm install
      
      - name: Test
        run: npm run test
